<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE module [
  <!ELEMENT module (dtdversion,name,version,description*,help*,about*,requires*,file+)>
  <!ELEMENT dtdversion (#PCDATA)>
  <!ELEMENT name (#PCDATA)>
  <!ELEMENT version (#PCDATA)>
  <!ELEMENT mincmsversion (#PCDATA)>
  <!ELEMENT description (#PCDATA)>
  <!ELEMENT help (#PCDATA)>
  <!ELEMENT about (#PCDATA)>
  <!ELEMENT requires (requiredname,requiredversion)>
  <!ELEMENT requiredname (#PCDATA)>
  <!ELEMENT requiredversion (#PCDATA)>
  <!ELEMENT file (filename,isdir,data)>
  <!ELEMENT filename (#PCDATA)>
  <!ELEMENT isdir (#PCDATA)>
  <!ELEMENT data (#PCDATA)>
]>
<module>
	<dtdversion>1.3</dtdversion>
	<name>Allinoneaccessibility</name>
	<version>1.0.6</version>
    <mincmsversion>2.2.21</mincmsversion>
	<help><![CDATA[]]></help>
	<about><![CDATA[PGJyIC8+QXV0aG9yOiBTa3luZXQgVGVjaG5vbG9naWVzIFVTQSBMTEMgJmx0O2hlbGxvQHNreW5ldHRlY2hub2xvZ2llcy5jb20gJmd0OzxiciAvPjxiciAvPlZlcnNpb246IDEuMC42PGJyIC8+]]></about>
	<description><![CDATA[All in One Accessibility widget improves website ADA compliance and browser experience for ADA, WCAG 2.1 & 2.2, Section 508, Australian DDA, European EAA EN 301 549, UK Equality Act (EA), Israeli Standard 5568, California Unruh, Ontario AODA, Canada ACA, German BITV, France RGAA, Brazilian Inclusion Law (LBI 13.146/2015), Spain UNE 139803:2012, JIS X 8341 (Japan), Italian Stanca Act and Switzerland DDA Standards. All in One Accessibility Widget complies with GDPR, COPPA regulations.]]></description>
	<file>
	  <filename>/</filename>
	  <isdir>1</isdir>
	</file>
	<file>
	  <filename>/action.defaultadmin.php</filename>
	  <isdir>0</isdir>
	  <data><![CDATA[PD9waHANCiMtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0NCiMgTW9kdWxlOiBBbGxpbm9uZWFjY2Vzc2liaWxpdHkNCiMgQXV0aG9yOiBTa3luZXQgVGVjaG5vbG9naWVzIFVTQSBMTEMNCiMgQ29weXJpZ2h0OiAoQykgMjAyMyBTa3luZXQgVGVjaG5vbG9naWVzIFVTQSBMTEMsIGhlbGxvQHNreW5ldHRlY2hub2xvZ2llcy5jb20NCiMgTGljZW5jZTogR05VIEdlbmVyYWwgUHVibGljIExpY2Vuc2UgdmVyc2lvbiAzDQojICAgICAgICAgIHNlZSAvQWxsaW5vbmVhY2Nlc3NpYmlsaXR5L2xhbmcvTElDRU5DRS50eHQgb3IgPGh0dHA6Ly93d3cuZ251Lm9yZy9saWNlbnNlcy9ncGwtMy4wLmh0bWw+DQojLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tDQoNCmlmKCAhZGVmaW5lZCgnQ01TX1ZFUlNJT04nKSApIGV4aXQ7DQoNCmlmKCAhJHRoaXMtPkNoZWNrUGVybWlzc2lvbihBbGxpbm9uZWFjY2Vzc2liaWxpdHk6Ok1BTkFHRV9QRVJNKSApIHJldHVybjsNCiAgICANCiRhaW9hX3dlYnNpdGVfaG9zdG5hbWUgPSBwYXJzZV91cmwoJGNvbmZpZ1sncm9vdF91cmwnXSwgUEhQX1VSTF9IT1NUKTsNCiANCiRjdXJsID0gY3VybF9pbml0KCk7DQpjdXJsX3NldG9wdF9hcnJheSgkY3VybCwgYXJyYXkoDQpDVVJMT1BUX1VSTCA9PiAnaHR0cHM6Ly9hZGEuc2t5bmV0dGVjaG5vbG9naWVzLnVzL2NoZWNrLXdlYnNpdGUnLA0KQ1VSTE9QVF9SRVRVUk5UUkFOU0ZFUiA9PiB0cnVlLA0KQ1VSTE9QVF9FTkNPRElORyA9PiAnJywNCkNVUkxPUFRfTUFYUkVESVJTID0+IDEwLA0KQ1VSTE9QVF9USU1FT1VUID0+IDAsDQpDVVJMT1BUX0ZPTExPV0xPQ0FUSU9OID0+IHRydWUsDQpDVVJMT1BUX0hUVFBfVkVSU0lPTiA9PiBDVVJMX0hUVFBfVkVSU0lPTl8xXzEsDQpDVVJMT1BUX0NVU1RPTVJFUVVFU1QgPT4gJ1BPU1QnLA0KQ1VSTE9QVF9QT1NURklFTERTID0+IGFycmF5KCdkb21haW4nID0+ICAkYWlvYV93ZWJzaXRlX2hvc3RuYW1lKSwNCikpOw0KDQokcmVzcG9uc2UgPSBjdXJsX2V4ZWMoJGN1cmwpOw0KDQpjdXJsX2Nsb3NlKCRjdXJsKTsNCiRzZXR0aW5nVVJMT2JqZWN0ID0ganNvbl9kZWNvZGUoJHJlc3BvbnNlKTsNCg0KIC8vIGZldGNoIFVzZXIgbmFtZSBhbmQgZW1haWwgDQogICAgaWYgKCFkZWZpbmVkKCdDTVNfVkVSU0lPTicpKSBleGl0Ow0KDQogICAgICAgICR1c2Vyb3BzID0gXFVzZXJPcGVyYXRpb25zOjpnZXRfaW5zdGFuY2UoKTsNCiAgICAgICAgJHVzZXJpZCA9IGdldF91c2VyaWQoKTsgLy8gZ2V0cyBjdXJyZW50IGxvZ2dlZC1pbiBhZG1pbiB1c2VyIElEDQoNCiAgICAgICAgaWYgKCR1c2VyaWQpIHsNCiAgICAgICAgICAgICR1c2VyMSA9ICR1c2Vyb3BzLT5Mb2FkVXNlckJ5SUQoJHVzZXJpZCk7DQogICAgICAgICR1c2VybmFtZSA9ICR1c2VyMS0+dXNlcm5hbWU7DQogICAgICAgICAgICAkZW1haWwgPSAkdXNlcjEtPmVtYWlsOw0KICAgICAgICB9IGVsc2Ugew0KICAgICAgICAgICAgZWNobyAnTm8gYWRtaW4gdXNlciBpcyBsb2dnZWQgaW4uJzsNCiAgICAgICAgfQ0KDQoNCiAgICAvLyBQcmVwYXJlIGRhdGEgb2JqZWN0IGZvciBTbWFydHkgdGVtcGxhdGUNCiAgICAkZGF0YU9iaiA9IFsNCiAgICAgICAgJ3VzZXJuYW1lJyA9PiAkdXNlcm5hbWUsDQogICAgICAgICdlbWFpbCcgPT4gJGVtYWlsLA0KICAgICAgICAnc2V0dGluZ2xpbmsnID0+ICRzZXR0aW5nVVJMT2JqZWN0LT5zZXR0aW5nbGluaywNCiAgICAgICAgJ3N0YXR1cycgPT4gJHNldHRpbmdVUkxPYmplY3QtPnN0YXR1cywNCiAgICAgICAgJ21hbmFnZV9kb21haW4nID0+ICRzZXR0aW5nVVJMT2JqZWN0LT5tYW5hZ2VfZG9tYWluLA0KICAgICAgICAnYWlvYV93ZWJzaXRlX2hvc3RuYW1lJyA9PiAkYWlvYV93ZWJzaXRlX2hvc3RuYW1lDQogICAgXTsNCg0KICAgIC8vIENvbnZlcnQgdG8gb2JqZWN0IGFuZCBhc3NpZ24gdG8gU21hcnR5IHRlbXBsYXRlDQogICAgJGRhdGEgPSAob2JqZWN0KSAkZGF0YU9iajsNCiAgICAkdHBsID0gJHNtYXJ0eS0+Q3JlYXRlVGVtcGxhdGUoJHRoaXMtPkdldFRlbXBsYXRlUmVzb3VyY2UoJ2RlZmF1bHRhZG1pbi50cGwnKSwgbnVsbCwgbnVsbCwgJHNtYXJ0eSk7DQogICAgJHRwbC0+YXNzaWduKCdkYXRhJywgJGRhdGEpOw0KICAgICR0cGwtPmRpc3BsYXkoKTsNCg0K]]></data>
	</file>
	<file>
	  <filename>/Allinoneaccessibility.module.php</filename>
	  <isdir>0</isdir>
	  <data><![CDATA[PD9waHANCiMtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0NCiMgTW9kdWxlOiBBbGxpbm9uZWFjY2Vzc2liaWxpdHkNCiMgQXV0aG9yOiBTa3luZXQgVGVjaG5vbG9naWVzIFVTQSBMTEMNCiMgQ29weXJpZ2h0OiAoQykgMjAyMyBTa3luZXQgVGVjaG5vbG9naWVzIFVTQSBMTEMsIGhlbGxvQHNreW5ldHRlY2hub2xvZ2llcy5jb20NCiMgTW9kdWxlJ3MgaG9tZXBhZ2UgaXM6IGh0dHA6Ly9kZXYuY21zbWFkZXNpbXBsZS5vcmcvcHJvamVjdHMvYWxsaW5vbmVhY2Nlc3NpYmlsaXR5DQojIExpY2VuY2U6IEdOVSBHZW5lcmFsIFB1YmxpYyBMaWNlbnNlIHZlcnNpb24gMw0KIyAgICAgICAgICBzZWUgL0FsbGlub25lYWNjZXNzaWJpbGl0eS9sYW5nL0xJQ0VOQ0UudHh0IG9yIDxodHRwOi8vd3d3LmdudS5vcmcvbGljZW5zZXMvPg0KIy0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQ0KIyBDTVMgLSBDTVMgTWFkZSBTaW1wbGUgaXMgKGMpIDIwMTkgYnkgQ01TIE1hZGUgU2ltcGxlIEZvdW5kYXRpb24gKGNvcHlyaWdodEBjbXNtYWRlc2ltcGxlLm9yZykNCiMgUHJvamVjdCdzIGhvbWVwYWdlIGlzOiBodHRwOi8vd3d3LmNtc21hZGVzaW1wbGUub3JnDQojLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tDQojIFRoaXMgcHJvZ3JhbSBpcyBmcmVlIHNvZnR3YXJlOyB5b3UgY2FuIHJlZGlzdHJpYnV0ZSBpdCBhbmQvb3IgbW9kaWZ5IGl0IHVuZGVyIHRoZSB0ZXJtcyBvZiB0aGUNCiMgR05VIEdlbmVyYWwgUHVibGljIExpY2Vuc2UgYXMgcHVibGlzaGVkIGJ5IHRoZSBGcmVlIFNvZnR3YXJlIEZvdW5kYXRpb247IGVpdGhlciB2ZXJzaW9uIDMNCiMgb2YgdGhlIExpY2Vuc2UsIG9yIChhdCB5b3VyIG9wdGlvbikgYW55IGxhdGVyIHZlcnNpb24uDQojDQojIFRoaXMgcHJvZ3JhbSBpcyBkaXN0cmlidXRlZCBpbiB0aGUgaG9wZSB0aGF0IGl0IHdpbGwgYmUgdXNlZnVsLCBidXQgV0lUSE9VVCBBTlkgV0FSUkFOVFk7DQojIHdpdGhvdXQgZXZlbiB0aGUgaW1wbGllZCB3YXJyYW50eSBvZiBNRVJDSEFOVEFCSUxJVFkgb3IgRklUTkVTUyBGT1IgQSBQQVJUSUNVTEFSIFBVUlBPU0UuDQojIFNlZSB0aGUgR05VIEdlbmVyYWwgUHVibGljIExpY2Vuc2UgZm9yIG1vcmUgZGV0YWlscy4NCiMNCiMgWW91IHNob3VsZCBoYXZlIHJlY2VpdmVkIGEgY29weSBvZiB0aGUgR05VIEdlbmVyYWwgUHVibGljIExpY2Vuc2UgYWxvbmcgd2l0aCB0aGlzIHByb2dyYW0uDQojIElmIG5vdCwgc2VlIDxodHRwOi8vd3d3LmdudS5vcmcvbGljZW5zZXMvPi4NCiMtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0NCg0KY2xhc3MgQWxsaW5vbmVhY2Nlc3NpYmlsaXR5IGV4dGVuZHMgQ01TTW9kdWxlDQp7DQogICAgY29uc3QgTUFOQUdFX1BFUk0gPSAnbWFuYWdlX2FsbGlub25lYWNjZXNzaWJpbGl0eSc7DQoNCiAgICBwdWJsaWMgZnVuY3Rpb24gR2V0VmVyc2lvbigpIHsgDQogICAgICAgIHJldHVybiAnMS4wLjYnOyANCiAgICB9DQoNCiAgICBwdWJsaWMgZnVuY3Rpb24gR2V0RnJpZW5kbHlOYW1lKCkgeyANCiAgICAgICAgcmV0dXJuICR0aGlzLT5MYW5nKCdmcmllbmRseW5hbWUnKTsgDQogICAgfQ0KDQogICAgcHVibGljIGZ1bmN0aW9uIEdldEFkbWluRGVzY3JpcHRpb24oKSB7IA0KICAgICAgICByZXR1cm4gJHRoaXMtPkxhbmcoJ2FkbWluZGVzY3JpcHRpb24nKTsgDQogICAgfQ0KDQogICAgcHVibGljIGZ1bmN0aW9uIElzUGx1Z2luTW9kdWxlKCkgeyANCiAgICAgICAgcmV0dXJuIFRSVUU7IA0KICAgIH0NCg0KICAgIHB1YmxpYyBmdW5jdGlvbiBIYXNBZG1pbigpIHsgDQogICAgICAgIHJldHVybiBUUlVFOyANCiAgICB9DQoNCiAgICBwdWJsaWMgZnVuY3Rpb24gVmlzaWJsZVRvQWRtaW5Vc2VyKCkgeyANCiAgICAgICAgcmV0dXJuICR0aGlzLT5DaGVja1Blcm1pc3Npb24oc2VsZjo6TUFOQUdFX1BFUk0pOyANCiAgICB9DQoNCiAgICBwdWJsaWMgZnVuY3Rpb24gR2V0QXV0aG9yKCkgeyANCiAgICAgICAgcmV0dXJuICdTa3luZXQgVGVjaG5vbG9naWVzIFVTQSBMTEMnOyANCiAgICB9DQoNCiAgICBwdWJsaWMgZnVuY3Rpb24gR2V0QXV0aG9yRW1haWwoKSB7IA0KICAgICAgICByZXR1cm4gJ2hlbGxvQHNreW5ldHRlY2hub2xvZ2llcy5jb20gJzsgDQogICAgfQ0KDQogICAgcHVibGljIGZ1bmN0aW9uIFVuaW5zdGFsbFByZU1lc3NhZ2UoKSB7IA0KICAgICAgICByZXR1cm4gJHRoaXMtPkxhbmcoJ2Fza191bmluc3RhbGwnKTsgDQogICAgfQ0KDQogICAgcHVibGljIGZ1bmN0aW9uIEluaXRpYWxpemVGcm9udGVuZCgpIHsNCiAgICAgICAgJHRoaXMtPlJlZ2lzdGVyTW9kdWxlUGx1Z2luKCk7DQogICAgICAgICAvLyBBZGQgQ1NTIGFuZCBKUyBmaWxlcyBoZXJlIGZvciB0aGUgZnJvbnRlbmQNCiAgICAgICAgJHRoaXMtPkFkZENTUygkdGhpcy0+R2V0TW9kdWxlVVJMUGF0aCgpIC4gJy9jc3MvYm9vdHN0cmFwLm1pbi5jc3MnKTsNCiAgICAgICAgJHRoaXMtPkFkZENTUygkdGhpcy0+R2V0TW9kdWxlVVJMUGF0aCgpIC4gJy9jc3Mvc3R5bGUuY3NzJyk7DQogICAgICAgICR0aGlzLT5BZGRIZWFkZXJKUygkdGhpcy0+R2V0TW9kdWxlVVJMUGF0aCgpIC4gJy9qcy9hbGxpbm9uZWFjY2Vzc2liaWxpdHkuanMnKTsNCiAgICAgICAgDQogICAgICAgIFxDTVNNU1xIb29rTWFuYWdlcjo6YWRkX2hvb2soJ0NvcmU6OkNvbnRlbnRQb3N0Q29tcGlsZScsIFskdGhpcywnUG9zdFJlbmRlckhvb2snXSk7DQogICAgfQ0KICAgIA0KICAgIHB1YmxpYyBmdW5jdGlvbiBHZXRBZG1pbkhlYWRlckhUTUwoKSB7DQogICAgICAgIC8vIEFkZCBDU1MgYW5kIEpTIHNwZWNpZmljIGZvciB0aGUgYWRtaW4gcGFuZWwNCiAgICAgICAgJGFkbWluX2NzcyA9ICR0aGlzLT5HZXRNb2R1bGVVUkxQYXRoKCkgLiAnL2Nzcy9ib290c3RyYXAubWluLmNzcyc7IC8vIEV4YW1wbGUgQ1NTIGZvciBhZG1pbg0KICAgICAgICAkYWRtaW5fY3NzID0gJHRoaXMtPkdldE1vZHVsZVVSTFBhdGgoKSAuICcvY3NzL3N0eWxlLmNzcyc7IC8vIEV4YW1wbGUgQ1NTIGZvciBhZG1pbg0KICAgICAgICAvLyBBZGQgdGhlIENTUyB0byB0aGUgYWRtaW4gcGFnZSBoZWFkZXINCiAgICAgICAgJHRoaXMtPkFkZENTUygkYWRtaW5fY3NzKTsNCiAgICAgICAgLy8gT3B0aW9uYWxseSwgeW91IGNhbiByZXR1cm4gY3VzdG9tIEhUTUwgKGxpa2UgYSA8c2NyaXB0PiB0YWcpIGluIHRoZSBhZG1pbiBoZWFkZXIgaWYgbmVjZXNzYXJ5DQogICAgICAgIHJldHVybiBwYXJlbnQ6OkdldEFkbWluSGVhZGVySFRNTCgpOyAvLyBBbHdheXMgY2FsbCB0aGUgcGFyZW50IHRvIGVuc3VyZSBvdGhlciBob29rcyBhcmUgcHJvY2Vzc2VkDQogICAgfQ0KICAgIA0KICAgIHB1YmxpYyBmdW5jdGlvbiBBZG1pbkRlZmF1bHQoJHBhcmFtcykgew0KICAgICAgICRzbWFydHktPmFzc2lnbignbW9kdWxlX3VybCcsICR0aGlzLT5HZXRNb2R1bGVVUkxQYXRoKCkpOw0KICAgICAgIHJldHVybiBwYXJlbnQ6OkFkbWluRGVmYXVsdCgpOw0KICAgIH0NCiAgICANCiAgICBwdWJsaWMgZnVuY3Rpb24gUG9zdFJlbmRlckhvb2soJHBhcmFtcykgew0KICAgICAgICANCiAgICAgICAgJHBhcmFtc1snY29udGVudCddID0gJzxzY3JpcHQgaWQ9ImFpb2EtYWRhd2lkZ2V0IiBzcmM9Imh0dHBzOi8vd3d3LnNreW5ldHRlY2hub2xvZ2llcy5jb20vYWNjZXNzaWJpbGl0eS9qcy9hbGwtaW4tb25lLWFjY2Vzc2liaWxpdHktanMtd2lkZ2V0LW1pbmlmeS5qcz9haW9hX3JlZ19yZXE9dHJ1ZSZjb2xvcmNvZGU9JnRva2VuPSZwb3NpdGlvbj1ib3R0b21fcmlnaHQiPjwvc2NyaXB0Pic7DQogICAgICAgIHJldHVybiAkcGFyYW1zOw0KICAgIH0NCiAgICANCiAgICANCiAgICANCn0=]]></data>
	</file>
	<file>
	  <filename>/css/</filename>
	  <isdir>1</isdir>
	</file>
	<file>
	  <filename>/css/allinoneaccessibility.css</filename>
	  <isdir>0</isdir>
	  <data><![CDATA[LmFsbC1pbi1vbmUtYWNjZXNzaWJpbGl0eS13cmFwIC5hY2Nlc3NpYmlsaXR5LXNldHRpbmdzIC5hbGwtb25lLWFjY2Vzc2liaWxpdHktZm9ybSB7CiAgICBtYXJnaW46IDAgYXV0byA0MHB4OwogICAgYm9yZGVyLXJhZGl1czogMTlweDsKICAgIGJhY2tncm91bmQ6ICNlOWVmZmY7CiAgICBwYWRkaW5nOiA0OHB4IDIycHggMTNweCA5OHB4Owp9Ci5haW9hLXNldHRpbmdzLXBhbmVsICNmb3JtLW1vZHVsZSAuZm9ybS1ncm91cCB7CiAgICBtYXJnaW4tYm90dG9tOiAzMHB4Owp9Ci5haW9hLXNldHRpbmdzLXBhbmVsICNmb3JtLW1vZHVsZSAuZm9ybS1ncm91cCBoMywKLmFpb2Etc2V0dGluZ3MtcGFuZWwgI2Zvcm0tbW9kdWxlIC5mb3JtLWdyb3VwIC5oM3sKICAgIGNvbG9yOiAjMWQyMzI3OwogICAgZm9udC1zaXplOiAxLjJyZW07CiAgICBmb250LXdlaWdodDogYm9sZDsKfQoKLmFpb2Etc2V0dGluZ3MtcGFuZWwgI2Zvcm0tbW9kdWxlIC5mb3JtLWdyb3VwIGZpZWxkc2V0IHsKICAgIGRpc3BsYXk6IGJsb2NrOwogICAgYm9yZGVyOiAxcHggc29saWQgI2MwYzBjMDsKICAgIHBvc2l0aW9uOiByZWxhdGl2ZTsKICAgIG1pbi13aWR0aDogMDsKICAgIG1hcmdpbi10b3A6IDFlbTsKICAgIHBhZGRpbmc6IDIwcHggMThweDsKICAgIGJvcmRlci1yYWRpdXM6IDJweDsKfQouYWlvYS1zZXR0aW5ncy1wYW5lbCAjZm9ybS1tb2R1bGUgLmZvcm0tZ3JvdXAgZmllbGRzZXQgbGVnZW5kIHsKICAgIGNvbG9yOiAjMWQyMzI3OwogICAgZm9udC1zaXplOiAxZW07CiAgICBmb250LXdlaWdodDogYm9sZDsKfQoKLmFsbGlub25lYWNjZXNzaWJpbGl0eS1maWVsZC13cmFwcGVyX19nbWFwLXdyYXBwZXIgewogICAgaGVpZ2h0OiA0MDBweDsKICAgIG1hcmdpbi10b3A6IDFyZW07Cn0KCi5hbGxpbm9uZWFjY2Vzc2liaWxpdHktZmllbGQtd3JhcHBlcl9fZ21hcCB7CiAgICB3aWR0aDogMTAwJTsKICAgIGhlaWdodDogMTAwJTsKfQoudGl0bGUtY29udGFpbmVyIHsKICAgIGRpc3BsYXk6IGZsZXg7CiAgICBqdXN0aWZ5LWNvbnRlbnQ6IGNlbnRlcjsgIC8qIENlbnRlcnMgaG9yaXpvbnRhbGx5ICovCiAgICBhbGlnbi1pdGVtczogY2VudGVyOyAgICAgIC8qIENlbnRlcnMgdmVydGljYWxseSAqLwogICAgaGVpZ2h0OiAxMDBweDsgICAgICAgICAgICAvKiBBZGp1c3QgdGhlIGhlaWdodCB0byBzdWl0IHlvdXIgZGVzaWduICovCiAgICBmb250LXNpemU6IDI0cHg7ICAgICAgICAgIC8qIEFkanVzdCB0aGUgZm9udCBzaXplICovCiAgICBmb250LXdlaWdodDogYm9sZDsKfQpodG1sLGJvZHl7CiAgICBmb250LXNpemU6IDEzcHQ7Cn0KLmFpb2Etc2V0dGluZ3MtcGFuZWwgLmlucHV0LWhpZGRlbiB7CiAgICBwb3NpdGlvbjogYWJzb2x1dGU7CiAgICBsZWZ0OiAtOTk5OXB4Owp9Ci5haW9hLXNldHRpbmdzLXBhbmVsIC5pY29uIGlucHV0W3R5cGU9cmFkaW9dICtsYWJlbHsKICAgIHdpZHRoOiAxMzBweDsKICAgIGhlaWdodDogMTMwcHg7CiAgICBwYWRkaW5nOiAxMHB4ICFpbXBvcnRhbnQ7CiAgICB0ZXh0LWFsaWduOiBjZW50ZXI7CiAgICBiYWNrZ3JvdW5kLWNvbG9yOiAjZjdmOWZmOwogICAgb3V0bGluZTogNHB4IHNvbGlkICNmN2Y5ZmY7CiAgICBvdXRsaW5lLW9mZnNldDogLTRweDsKICAgIGJvcmRlci1yYWRpdXM6IDEwcHg7CiAgICBiYWNrZ3JvdW5kOiAjNDIwMDgzOwp9Ci5haW9hLXNldHRpbmdzLXBhbmVsIC5pY29uIGlucHV0W3R5cGU9cmFkaW9dOmNoZWNrZWQrbGFiZWwgewogICAgb3V0bGluZS1jb2xvcjogIzgwYzk0NDsKICAgIHBvc2l0aW9uOiByZWxhdGl2ZTsKfQoKLmFpb2Etc2V0dGluZ3MtcGFuZWwgLmljb24gaW5wdXRbdHlwZT1yYWRpb106Y2hlY2tlZCtsYWJlbDo6YmVmb3JlIHsKCiAgICBjb250ZW50OiAiIjsKICAgIHdpZHRoOiAyMHB4OwogICAgaGVpZ2h0OiAyMHB4OwogICAgcG9zaXRpb246IGFic29sdXRlOwogICAgbGVmdDogYXV0bzsKICAgIHJpZ2h0OiAtNHB4OwogICAgdG9wOiAtNHB4OwogICAgYmFja2dyb3VuZDogdXJsKCJkYXRhOmltYWdlL3N2Zyt4bWwsJTNDc3ZnIHhtbG5zPSdodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2Zycgdmlld0JveD0nMCAwIDI1IDI1JyBjbGFzcz0nYWlvYS1mZWF0dXJlLW9uJyUzRSUzQ2clM0UlM0NjaXJjbGUgZmlsbD0nJTIzNDNBMDQ3JyBjeD0nMTIuNScgY3k9JzEyLjUnIHI9JzEyJyUzRSUzQy9jaXJjbGUlM0UlM0NwYXRoIGZpbGw9JyUyM0ZGRkZGRicgZD0nTTEyLjUsMUMxOC45LDEsMjQsNi4xLDI0LDEyLjVTMTguOSwyNCwxMi41LDI0UzEsMTguOSwxLDEyLjVTNi4xLDEsMTIuNSwxIE0xMi41LDBDNS42LDAsMCw1LjYsMCwxMi41UzUuNiwyNSwxMi41LDI1UzI1LDE5LjQsMjUsMTIuNVMxOS40LDAsMTIuNSwwTDEyLjUsMHonJTNFJTNDL3BhdGglM0UlM0MvZyUzRSUzQ3BvbHlnb24gZmlsbD0nJTIzRkZGRkZGJyBwb2ludHM9JzkuOCwxOS40IDkuOCwxOS40IDkuOCwxOS40IDQuNCwxMy45IDcuMSwxMS4xIDkuOCwxMy45IDE3LjksNS42IDIwLjUsOC40ICclM0UlM0MvcG9seWdvbiUzRSUzQy9zdmclM0UiKSBuby1yZXBlYXQgY2VudGVyIGNlbnRlci9jb250YWluICFpbXBvcnRhbnQ7CiAgICBib3JkZXI6IG5vbmU7Cn0KCi8qIElNQUdFIFNUWUxFUyAqLwouYWlvYS1zZXR0aW5ncy1wYW5lbCBpbnB1dFt0eXBlPXJhZGlvXStsYWJlbD5pbWcgewogICAgY3Vyc29yOiBwb2ludGVyOwogICAgd2lkdGg6IHJldmVydC1sYXllcjsKICAgIGhlaWdodDogcmV2ZXJ0LWxheWVyOwp9CgouYWlvYS1zZXR0aW5ncy1wYW5lbCAuaWNvbi1sYWJlbCB7CiAgICBkaXNwbGF5OiBmbGV4OwogICAganVzdGlmeS1jb250ZW50OiBjZW50ZXI7CiAgICBoZWlnaHQ6IDkwcHg7CiAgICB3aWR0aDogOTBweDsKICAgIGJvcmRlcjogMnB4IHNvbGlkIGdyYXk7CiAgICBib3JkZXItcmFkaXVzOiAzcHg7Cn0KCi5kLW5vbmUgewogICAgZGlzcGxheTogbm9uZTsKfQoKLmFpb2Etc2V0dGluZ3MtcGFuZWwgewogICAgZm9udC1mYW1pbHk6IHN5c3RlbS11aSwgLWFwcGxlLXN5c3RlbSwgIlNlZ29lIFVJIiwgUm9ib3RvLCAiSGVsdmV0aWNhIE5ldWUiLCAiTm90byBTYW5zIiwgIkxpYmVyYXRpb24gU2FucyIsIEFyaWFsLCBzYW5zLXNlcmlmLCAiQXBwbGUgQ29sb3IgRW1vamkiLCAiU2Vnb2UgVUkgRW1vamkiLCAiU2Vnb2UgVUkgU3ltYm9sIiwgIk5vdG8gQ29sb3IgRW1vamkiOwogICAgYm94LXNpemluZzogYm9yZGVyLWJveDsKfQoKLmFpb2Etc2V0dGluZ3MtcGFuZWwgKiwKLmFpb2Etc2V0dGluZ3MtcGFuZWwgKjo6YWZ0ZXIsCi5haW9hLXNldHRpbmdzLXBhbmVsICo6OmJlZm9yZSB7CiAgICBib3gtc2l6aW5nOiBib3JkZXItYm94Owp9CgouYWlvYS1zZXR0aW5ncy1wYW5lbCAucm93IHsKICAgIGRpc3BsYXk6IGZsZXg7CiAgICBmbGV4LXdyYXA6IHdyYXA7CiAgICBtYXJnaW4tbGVmdDogLTAuNzVyZW07CiAgICBtYXJnaW4tcmlnaHQ6IC0wLjc1cmVtOwp9CgouYWlvYS1zZXR0aW5ncy1wYW5lbCAucm93PiogewogICAgcG9zaXRpb246IHJlbGF0aXZlOwogICAgcGFkZGluZy1yaWdodDogMC43NXJlbTsKICAgIHBhZGRpbmctbGVmdDogMC43NXJlbTsKfQoKCkBtZWRpYSBzY3JlZW4gYW5kIChtaW4td2lkdGg6NTc2cHgpIHsKICAgIC5haW9hLXNldHRpbmdzLXBhbmVsIC5jb2wtc20tMiB7CiAgICAgICAgZmxleDogMCAwIGF1dG87CiAgICAgICAgd2lkdGg6IDE2LjY2NjY2JTsKICAgIH0KCiAgICAuYWlvYS1zZXR0aW5ncy1wYW5lbCAuY29sLXNtLTEwIHsKICAgICAgICBmbGV4OiAwIDAgYXV0bzsKICAgICAgICB3aWR0aDogODMuMzMzMzMlOwogICAgfQoKICAgIC5haW9hLXNldHRpbmdzLXBhbmVsIC5jb2wtc20tOCB7CiAgICAgICAgZmxleDogMCAwIGF1dG87CiAgICAgICAgd2lkdGg6IDY2LjY2NjYlOwogICAgfQoKICAgIC5haW9hLXNldHRpbmdzLXBhbmVsIC5jb2wtc20tMyB7CiAgICAgICAgZmxleDogMCAwIGF1dG87CiAgICAgICAgd2lkdGg6IDI1JTsKICAgIH0KfQoKCi5haW9hLXNldHRpbmdzLXBhbmVsIC5mb3JtLWNvbnRyb2w6Zm9jdXMgewogICAgYm9yZGVyLWNvbG9yOiByZ2JhKDY2LCAwLCAxMzEsIC4zODAzOTIxNTY5KTsKICAgIGJveC1zaGFkb3c6IDAgMCAwIDAuMjVyZW0gcmdiYSg2NiwgMCwgMTMxLCAuMik7CiAgICBvdXRsaW5lOiAwOwp9CgouYWlvYS1zZXR0aW5ncy1wYW5lbCAudmlzdWFsbHktaGlkZGVuLAouYWlvYS1zZXR0aW5ncy1wYW5lbCAudmlzdWFsbHktaGlkZGVuLWZvY3VzYWJsZTpub3QoOmZvY3VzKTpub3QoOmZvY3VzLXdpdGhpbikgewogICAgcG9zaXRpb246IGFic29sdXRlICFpbXBvcnRhbnQ7CiAgICB3aWR0aDogMXB4ICFpbXBvcnRhbnQ7CiAgICBoZWlnaHQ6IDFweCAhaW1wb3J0YW50OwogICAgcGFkZGluZzogMCAhaW1wb3J0YW50OwogICAgbWFyZ2luOiAtMXB4ICFpbXBvcnRhbnQ7CiAgICBvdmVyZmxvdzogaGlkZGVuICFpbXBvcnRhbnQ7CiAgICBjbGlwOiByZWN0KDAsIDAsIDAsIDApICFpbXBvcnRhbnQ7CiAgICB3aGl0ZS1zcGFjZTogbm93cmFwICFpbXBvcnRhbnQ7CiAgICBib3JkZXI6IDAgIWltcG9ydGFudDsKfQouZC1ub25lewogICAgZGlzcGxheTpub25lICFpbXBvcnRhbnQ7Cn0KI3NldHRpbmdzLWludmFsaWQta2V5LW1zZ3sKICAgIGNvbG9yOnJlZDsKfQojc2V0dGluZ3MtbGljZW5zZV9rZXlfbXNnewogICAgbWFyZ2luLXRvcCA6IDAuMXJlbTsKICAgIHRleHQtYWxpZ246IGNlbnRlcjsKfQoubG9hZGluZyB7CiAgICBwb3NpdGlvbjogZml4ZWQ7CiAgICBkaXNwbGF5OiBmbGV4OwogICAganVzdGlmeS1jb250ZW50OiBjZW50ZXI7CiAgICBhbGlnbi1pdGVtczogY2VudGVyOwogICAgd2lkdGg6IDEwMCU7CiAgICBoZWlnaHQ6IDEwMCU7CiAgICB0b3A6IDA7CiAgICBsZWZ0OiAwOwogICAgb3BhY2l0eTogMC43OwogICAgYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsKICAgIHotaW5kZXg6IDk5Owp9CgoubG9hZGluZy1pbWFnZSB7CiAgICB6LWluZGV4OiAxMDA7Cn0KTEFCRUwgewogICAgRElTUExBWTogLXdlYmtpdC1pbmxpbmUtYm94Owp9CkJVVFRPTiwgSU5QVVRbdHlwZT1zdWJtaXRdLCBJTlBVVFt0eXBlPWNsZWFyXSwgSU5QVVRbdHlwZT1idXR0b25dLCBJTlBVVFt0eXBlPXJlc2V0XSB7CiAgICBQQURESU5HLVJJR0hUOiAwLjVlbTsKICAgIFBBRERJTkctTEVGVDogMC41ZW07CiAgICBQQURESU5HLUJPVFRPTTogMnB4OwogICAgUEFERElORy1UT1A6IDJweDsKICAgIHBhZGRpbmc6IDElOwogICAgYmFja2dyb3VuZC1jb2xvcjogIzY4YTI0ZTsKICAgIEJBQ0tHUk9VTkQtSU1BR0U6IHVybChpbWFnZXMvdGFibGUtY2FwdGlvbi1ncmV5LnBuZyk7CiAgICBCQUNLR1JPVU5ELVBPU0lUSU9OOiBib3R0b207CiAgICBCQUNLR1JPVU5ELVJFUEVBVDogcmVwZWF0LXg7CiAgICBDT0xPUjogI2ZmZmZmZjsKICAgIEZPTlQtV0VJR0hUOiBib2xkOwogICAgQ1VSU09SOiBwb2ludGVyOwogICAgQk9SREVSOiBvdXRzZXQgNHB4ICNiZWQ4YjI7Cn0KCi50aHJlZS1jb2wgewogICAgY29sdW1uLWNvdW50OiAzOwogICAgY29sdW1uLWdhcDogM3JlbTsKfQoudGhyZWUtY29sPiogewogICAgLXdlYmtpdC1jb2x1bW4tYnJlYWstaW5zaWRlOiBhdm9pZDsKICAgIHBhZ2UtYnJlYWstaW5zaWRlOiBhdm9pZDsKICAgIGJyZWFrLWluc2lkZTogYXZvaWQ7Cn0KLmljb24tcG9zaXRpb24tcmFkaW9zIHsKICAgIG1heC13aWR0aDogNTUwcHg7Cn0KLmliZXhhLW1haW4tY29udGFpbmVyX19jb250ZW50LWNvbHVtbiA+IC5jb250YWluZXIgewogICAgbWF4LXdpZHRoOiBub25lOwp9Ci5wYW5lbC1ib2R5ewogICAgcGFkZGluZzogMSU7Cn0K]]></data>
	</file>
	<file>
	  <filename>/css/bootstrap.min.css</filename>
	  <isdir>0</isdir>